"""
Database initialization script
Run this to create tables and optionally seed with sample data
"""
from database import engine
from models import Base, JobListing
from sqlalchemy.orm import sessionmaker
from datetime import datetime, timedelta

def init_database():
    """Create all database tables"""
    print("Creating database tables...")
    Base.metadata.create_all(bind=engine)
    print("Database tables created successfully!")


def seed_sample_data():
    """Seed database with sample job listings"""
    print("Seeding sample data...")

    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()

    # Check if data already exists
    existing = db.query(JobListing).first()
    if existing:
        print("Sample data already exists. Skipping...")
        db.close()
        return

    # Sample job listings
    sample_jobs = [
        JobListing(
            nlx_id="NLX0001",
            title="Data Analyst",
            company="3M",
            description="Analyze manufacturing and supply chain data to uncover trends and drive process improvements.",
            location="Saint Paul, MN",
            city="Saint Paul",
            state="MN",
            zip_code="55101",
            latitude=44.9537,
            longitude=-93.0900,
            industry="Manufacturing",
            occupation="Data Analysis",
            occupation_code="15-2051.00",
            salary_min=78000,
            salary_max=112000,
            employment_type="Full-time",
            required_skills=["Python", "SQL", "Excel", "Statistics"],
            education_required="Bachelor's degree",
            experience_required="3+ years",
            aoi_overall_badge="Gold",
            aoi_badge_early_career="NA",
            aoi_badge_growth="NA",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.142381,
            aoi_external_promotion_rate=0.071204,
            aoi_retention_rate_3yr=0.861224,
            remote_work=False,
            posted_date=datetime.utcnow() - timedelta(days=3),
            expires_date=datetime.utcnow() + timedelta(days=27),
            url="https://example.com/jobs/3m/0001",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0002",
            title="Quality Systems Engineer",
            company="3M",
            description="Develop and maintain quality control systems to ensure product compliance and reliability.",
            location="Saint Paul, MN",
            city="Saint Paul",
            state="MN",
            zip_code="55144",
            latitude=44.9631,
            longitude=-93.1022,
            industry="Manufacturing",
            occupation="Industrial Engineering",
            occupation_code="17-2112.00",
            salary_min=85000,
            salary_max=125000,
            employment_type="Full-time",
            required_skills=[
                "Six Sigma",
                "Root Cause Analysis",
                "ISO Standards",
                "Process Mapping",
            ],
            education_required="Bachelor's degree in Engineering",
            experience_required="5+ years",
            aoi_overall_badge="Gold",
            aoi_badge_early_career="NA",
            aoi_badge_growth="NA",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.151993,
            aoi_external_promotion_rate=0.063882,
            aoi_retention_rate_3yr=0.874221,
            remote_work=False,
            posted_date=datetime.utcnow() - timedelta(days=6),
            expires_date=datetime.utcnow() + timedelta(days=24),
            url="https://example.com/jobs/3m/0002",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0003",
            title="Clinical Data Specialist",
            company="Abbott Laboratories",
            description="Manage and validate clinical datasets used in medical device research and regulatory submissions.",
            location="Chicago, IL",
            city="Chicago",
            state="IL",
            zip_code="60601",
            latitude=41.8781,
            longitude=-87.6298,
            industry="Medical Devices",
            occupation="Clinical Research",
            occupation_code="19-1042.00",
            salary_min=82000,
            salary_max=118000,
            employment_type="Full-time",
            required_skills=["SAS", "Clinical Data Management", "GCP", "SQL"],
            education_required="Bachelor's degree in Life Sciences",
            experience_required="3+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="NA",
            aoi_badge_growth="Gold",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.163552,
            aoi_external_promotion_rate=0.059114,
            aoi_retention_rate_3yr=0.902341,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=4),
            expires_date=datetime.utcnow() + timedelta(days=30),
            url="https://example.com/jobs/abbott/0003",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0004",
            title="Regulatory Affairs Manager",
            company="Abbott Laboratories",
            description="Lead regulatory strategy and submissions for new and updated medical products.",
            location="Chicago, IL",
            city="Chicago",
            state="IL",
            zip_code="60606",
            latitude=41.8827,
            longitude=-87.6376,
            industry="Medical Devices",
            occupation="Regulatory Affairs",
            occupation_code="13-1041.00",
            salary_min=105000,
            salary_max=155000,
            employment_type="Full-time",
            required_skills=[
                "FDA Regulations",
                "Technical Writing",
                "Risk Assessment",
                "Project Management",
            ],
            education_required="Bachelor's degree",
            experience_required="7+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="NA",
            aoi_badge_growth="Gold",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.172204,
            aoi_external_promotion_rate=0.048771,
            aoi_retention_rate_3yr=0.911553,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=8),
            expires_date=datetime.utcnow() + timedelta(days=22),
            url="https://example.com/jobs/abbott/0004",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0005",
            title="Bioinformatics Analyst",
            company="AbbVie",
            description="Analyze genomic and clinical datasets to support drug discovery and development.",
            location="North Chicago, IL",
            city="North Chicago",
            state="IL",
            zip_code="60064",
            latitude=42.3256,
            longitude=-87.8412,
            industry="Pharmaceuticals",
            occupation="Bioinformatics",
            occupation_code="15-2041.00",
            salary_min=98000,
            salary_max=142000,
            employment_type="Full-time",
            required_skills=["Python", "R", "Genomics", "Data Visualization"],
            education_required="Master's degree preferred",
            experience_required="4+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="NA",
            aoi_badge_growth="Platinum",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.181442,
            aoi_external_promotion_rate=0.052991,
            aoi_retention_rate_3yr=0.918774,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=2),
            expires_date=datetime.utcnow() + timedelta(days=33),
            url="https://example.com/jobs/abbvie/0005",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0006",
            title="Pharmacovigilance Specialist",
            company="AbbVie",
            description="Monitor and evaluate drug safety data to ensure compliance with global safety regulations.",
            location="North Chicago, IL",
            city="North Chicago",
            state="IL",
            zip_code="60085",
            latitude=42.3301,
            longitude=-87.8503,
            industry="Pharmaceuticals",
            occupation="Drug Safety",
            occupation_code="29-9011.00",
            salary_min=88000,
            salary_max=126000,
            employment_type="Full-time",
            required_skills=[
                "Case Processing",
                "Signal Detection",
                "Medical Terminology",
                "Compliance",
            ],
            education_required="Bachelor's degree in Pharmacy or Life Sciences",
            experience_required="3+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="NA",
            aoi_badge_growth="Platinum",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.169335,
            aoi_external_promotion_rate=0.061447,
            aoi_retention_rate_3yr=0.907112,
            remote_work=False,
            posted_date=datetime.utcnow() - timedelta(days=7),
            expires_date=datetime.utcnow() + timedelta(days=21),
            url="https://example.com/jobs/abbvie/0006",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0007",
            title="Cloud Solutions Architect",
            company="Accenture",
            description="Design scalable cloud architectures and guide enterprise cloud transformation projects.",
            location="New York, NY",
            city="New York",
            state="NY",
            zip_code="10020",
            latitude=40.7580,
            longitude=-73.9855,
            industry="Professional Services",
            occupation="Cloud Architecture",
            occupation_code="15-1241.00",
            salary_min=125000,
            salary_max=185000,
            employment_type="Full-time",
            required_skills=["AWS", "Azure", "Microservices", "DevOps"],
            education_required="Bachelor's degree",
            experience_required="6+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="Gold",
            aoi_badge_growth="Platinum",
            aoi_badge_stability="Gold",
            aoi_interal_promption_rate=0.158441,
            aoi_external_promotion_rate=0.079335,
            aoi_retention_rate_3yr=0.843551,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=5),
            expires_date=datetime.utcnow() + timedelta(days=29),
            url="https://example.com/jobs/accenture/0007",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0008",
            title="Business Transformation Consultant",
            company="Accenture",
            description="Advise clients on operational redesign and digital transformation initiatives.",
            location="New York, NY",
            city="New York",
            state="NY",
            zip_code="10036",
            latitude=40.7590,
            longitude=-73.9845,
            industry="Professional Services",
            occupation="Management Consulting",
            occupation_code="13-1111.00",
            salary_min=98000,
            salary_max=150000,
            employment_type="Full-time",
            required_skills=[
                "Process Improvement",
                "Change Management",
                "Analytics",
                "Stakeholder Engagement",
            ],
            education_required="Bachelor's degree",
            experience_required="4+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="Gold",
            aoi_badge_growth="Platinum",
            aoi_badge_stability="Gold",
            aoi_interal_promption_rate=0.144002,
            aoi_external_promotion_rate=0.083551,
            aoi_retention_rate_3yr=0.829441,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=9),
            expires_date=datetime.utcnow() + timedelta(days=18),
            url="https://example.com/jobs/accenture/0008",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0001",
            title="Data Analyst",
            company="3M",
            description="Analyze manufacturing and supply chain data to uncover trends and drive process improvements.",
            location="Saint Paul, MN",
            city="Saint Paul",
            state="MN",
            zip_code="55101",
            latitude=44.9537,
            longitude=-93.0900,
            industry="Manufacturing",
            occupation="Data Analysis",
            occupation_code="15-2051.00",
            salary_min=78000,
            salary_max=112000,
            employment_type="Full-time",
            required_skills=["Python", "SQL", "Excel", "Statistics"],
            education_required="Bachelor's degree",
            experience_required="3+ years",
            aoi_overall_badge="Gold",
            aoi_badge_early_career="NA",
            aoi_badge_growth="NA",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.142381,
            aoi_external_promotion_rate=0.071204,
            aoi_retention_rate_3yr=0.861224,
            remote_work=False,
            posted_date=datetime.utcnow() - timedelta(days=3),
            expires_date=datetime.utcnow() + timedelta(days=27),
            url="https://example.com/jobs/3m/0001",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0002",
            title="Quality Systems Engineer",
            company="3M",
            description="Develop and maintain quality control systems to ensure product compliance and reliability.",
            location="Saint Paul, MN",
            city="Saint Paul",
            state="MN",
            zip_code="55144",
            latitude=44.9631,
            longitude=-93.1022,
            industry="Manufacturing",
            occupation="Industrial Engineering",
            occupation_code="17-2112.00",
            salary_min=85000,
            salary_max=125000,
            employment_type="Full-time",
            required_skills=[
                "Six Sigma",
                "Root Cause Analysis",
                "ISO Standards",
                "Process Mapping",
            ],
            education_required="Bachelor's degree in Engineering",
            experience_required="5+ years",
            aoi_overall_badge="Gold",
            aoi_badge_early_career="NA",
            aoi_badge_growth="NA",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.151993,
            aoi_external_promotion_rate=0.063882,
            aoi_retention_rate_3yr=0.874221,
            remote_work=False,
            posted_date=datetime.utcnow() - timedelta(days=6),
            expires_date=datetime.utcnow() + timedelta(days=24),
            url="https://example.com/jobs/3m/0002",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0003",
            title="Clinical Data Specialist",
            company="Abbott Laboratories",
            description="Manage and validate clinical datasets used in medical device research and regulatory submissions.",
            location="Chicago, IL",
            city="Chicago",
            state="IL",
            zip_code="60601",
            latitude=41.8781,
            longitude=-87.6298,
            industry="Medical Devices",
            occupation="Clinical Research",
            occupation_code="19-1042.00",
            salary_min=82000,
            salary_max=118000,
            employment_type="Full-time",
            required_skills=["SAS", "Clinical Data Management", "GCP", "SQL"],
            education_required="Bachelor's degree in Life Sciences",
            experience_required="3+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="NA",
            aoi_badge_growth="Gold",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.163552,
            aoi_external_promotion_rate=0.059114,
            aoi_retention_rate_3yr=0.902341,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=4),
            expires_date=datetime.utcnow() + timedelta(days=30),
            url="https://example.com/jobs/abbott/0003",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0004",
            title="Regulatory Affairs Manager",
            company="Abbott Laboratories",
            description="Lead regulatory strategy and submissions for new and updated medical products.",
            location="Chicago, IL",
            city="Chicago",
            state="IL",
            zip_code="60606",
            latitude=41.8827,
            longitude=-87.6376,
            industry="Medical Devices",
            occupation="Regulatory Affairs",
            occupation_code="13-1041.00",
            salary_min=105000,
            salary_max=155000,
            employment_type="Full-time",
            required_skills=[
                "FDA Regulations",
                "Technical Writing",
                "Risk Assessment",
                "Project Management",
            ],
            education_required="Bachelor's degree",
            experience_required="7+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="NA",
            aoi_badge_growth="Gold",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.172204,
            aoi_external_promotion_rate=0.048771,
            aoi_retention_rate_3yr=0.911553,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=8),
            expires_date=datetime.utcnow() + timedelta(days=22),
            url="https://example.com/jobs/abbott/0004",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0005",
            title="Bioinformatics Analyst",
            company="AbbVie",
            description="Analyze genomic and clinical datasets to support drug discovery and development.",
            location="North Chicago, IL",
            city="North Chicago",
            state="IL",
            zip_code="60064",
            latitude=42.3256,
            longitude=-87.8412,
            industry="Pharmaceuticals",
            occupation="Bioinformatics",
            occupation_code="15-2041.00",
            salary_min=98000,
            salary_max=142000,
            employment_type="Full-time",
            required_skills=["Python", "R", "Genomics", "Data Visualization"],
            education_required="Master's degree preferred",
            experience_required="4+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="NA",
            aoi_badge_growth="Platinum",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.181442,
            aoi_external_promotion_rate=0.052991,
            aoi_retention_rate_3yr=0.918774,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=2),
            expires_date=datetime.utcnow() + timedelta(days=33),
            url="https://example.com/jobs/abbvie/0005",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0006",
            title="Cloud Solutions Architect",
            company="Accenture",
            description="Design scalable cloud architectures and guide enterprise cloud transformation projects.",
            location="New York, NY",
            city="New York",
            state="NY",
            zip_code="10020",
            latitude=40.7580,
            longitude=-73.9855,
            industry="Professional Services",
            occupation="Cloud Architecture",
            occupation_code="15-1241.00",
            salary_min=125000,
            salary_max=185000,
            employment_type="Full-time",
            required_skills=["AWS", "Azure", "Microservices", "DevOps"],
            education_required="Bachelor's degree",
            experience_required="6+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="Gold",
            aoi_badge_growth="Platinum",
            aoi_badge_stability="Gold",
            aoi_interal_promption_rate=0.158441,
            aoi_external_promotion_rate=0.079335,
            aoi_retention_rate_3yr=0.843551,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=5),
            expires_date=datetime.utcnow() + timedelta(days=29),
            url="https://example.com/jobs/accenture/0006",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0007",
            title="Senior Software Engineer",
            company="Adobe",
            description="Build high-performance services powering creative cloud applications.",
            location="San Jose, CA",
            city="San Jose",
            state="CA",
            zip_code="95110",
            latitude=37.3382,
            longitude=-121.8863,
            industry="Software",
            occupation="Software Development",
            occupation_code="15-1252.00",
            salary_min=135000,
            salary_max=195000,
            employment_type="Full-time",
            required_skills=["Java", "Distributed Systems", "APIs", "Cloud"],
            education_required="Bachelor's degree in Computer Science",
            experience_required="5+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="NA",
            aoi_badge_growth="Platinum",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.176551,
            aoi_external_promotion_rate=0.062114,
            aoi_retention_rate_3yr=0.912882,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=4),
            expires_date=datetime.utcnow() + timedelta(days=31),
            url="https://example.com/jobs/adobe/0007",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0008",
            title="HR Data Analyst",
            company="ADP",
            description="Deliver workforce analytics dashboards and insights for enterprise HR teams.",
            location="Roseland, NJ",
            city="Roseland",
            state="NJ",
            zip_code="07068",
            latitude=40.8209,
            longitude=-74.2932,
            industry="HR Technology",
            occupation="Data Analysis",
            occupation_code="15-2051.00",
            salary_min=72000,
            salary_max=104000,
            employment_type="Full-time",
            required_skills=["SQL", "Tableau", "Excel", "Reporting"],
            education_required="Bachelor's degree",
            experience_required="3+ years",
            aoi_overall_badge="Gold",
            aoi_badge_early_career="Gold",
            aoi_badge_growth="Platinum",
            aoi_badge_stability="NA",
            aoi_interal_promption_rate=0.149002,
            aoi_external_promotion_rate=0.081225,
            aoi_retention_rate_3yr=0.824551,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=10),
            expires_date=datetime.utcnow() + timedelta(days=20),
            url="https://example.com/jobs/adp/0008",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0009",
            title="GPU Compiler Engineer",
            company="Advanced Micro Devices",
            description="Optimize compiler pipelines for next-generation GPU architectures.",
            location="Santa Clara, CA",
            city="Santa Clara",
            state="CA",
            zip_code="95054",
            latitude=37.3541,
            longitude=-121.9552,
            industry="Semiconductors",
            occupation="Software Engineering",
            occupation_code="15-1252.00",
            salary_min=145000,
            salary_max=210000,
            employment_type="Full-time",
            required_skills=["C++", "Compilers", "Parallel Computing", "Linux"],
            education_required="Bachelor's degree in Computer Engineering",
            experience_required="5+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="Gold",
            aoi_badge_growth="NA",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.162331,
            aoi_external_promotion_rate=0.058442,
            aoi_retention_rate_3yr=0.889221,
            remote_work=False,
            posted_date=datetime.utcnow() - timedelta(days=1),
            expires_date=datetime.utcnow() + timedelta(days=35),
            url="https://example.com/jobs/amd/0009",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0010",
            title="Marketplace Trust & Safety Analyst",
            company="Airbnb",
            description="Investigate risk signals and improve platform safety for hosts and guests.",
            location="San Francisco, CA",
            city="San Francisco",
            state="CA",
            zip_code="94103",
            latitude=37.7749,
            longitude=-122.4194,
            industry="Hospitality Technology",
            occupation="Risk Analysis",
            occupation_code="13-2099.00",
            salary_min=88000,
            salary_max=128000,
            employment_type="Full-time",
            required_skills=["Fraud Detection", "SQL", "Investigation", "Policy"],
            education_required="Bachelor's degree",
            experience_required="3+ years",
            aoi_overall_badge="Gold",
            aoi_badge_early_career="NA",
            aoi_badge_growth="NA",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.137551,
            aoi_external_promotion_rate=0.066221,
            aoi_retention_rate_3yr=0.852771,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=6),
            expires_date=datetime.utcnow() + timedelta(days=26),
            url="https://example.com/jobs/airbnb/0010",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0011",
            title="Digital Banking Product Manager",
            company="Ally Financial",
            description="Own roadmap for mobile-first banking experiences.",
            location="Detroit, MI",
            city="Detroit",
            state="MI",
            zip_code="48226",
            latitude=42.3314,
            longitude=-83.0458,
            industry="Financial Services",
            occupation="Product Management",
            occupation_code="11-2021.00",
            salary_min=110000,
            salary_max=165000,
            employment_type="Full-time",
            required_skills=["Product Strategy", "Agile", "Analytics", "UX"],
            education_required="Bachelor's degree",
            experience_required="5+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="Gold",
            aoi_badge_growth="Platinum",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.174551,
            aoi_external_promotion_rate=0.049882,
            aoi_retention_rate_3yr=0.903551,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=3),
            expires_date=datetime.utcnow() + timedelta(days=32),
            url="https://example.com/jobs/ally/0011",
            extra_data={"generated": True},
        ),
        JobListing(
            nlx_id="NLX0012",
            title="Distributed Systems Engineer",
            company="Amazon",
            description="Design resilient large-scale services supporting global e-commerce traffic.",
            location="Seattle, WA",
            city="Seattle",
            state="WA",
            zip_code="98101",
            latitude=47.6062,
            longitude=-122.3321,
            industry="Technology",
            occupation="Software Development",
            occupation_code="15-1252.00",
            salary_min=155000,
            salary_max=220000,
            employment_type="Full-time",
            required_skills=["Java", "Microservices", "AWS", "NoSQL"],
            education_required="Bachelor's degree in Computer Science",
            experience_required="5+ years",
            aoi_overall_badge="Platinum",
            aoi_badge_early_career="NA",
            aoi_badge_growth="Platinum",
            aoi_badge_stability="Platinum",
            aoi_interal_promption_rate=0.168772,
            aoi_external_promotion_rate=0.057221,
            aoi_retention_rate_3yr=0.881114,
            remote_work=True,
            posted_date=datetime.utcnow() - timedelta(days=2),
            expires_date=datetime.utcnow() + timedelta(days=40),
            url="https://example.com/jobs/amazon/0012",
            extra_data={"generated": True},
        ),
    ]

    # Add to database
    for job in sample_jobs:
        db.add(job)

    db.commit()
    print(f"Added {len(sample_jobs)} sample job listings!")
    db.close()


if __name__ == "__main__":
    init_database()
    
    # Ask if user wants to seed sample data
    response = input("\nWould you like to seed sample job data? (y/n): ")
    if response.lower() == 'y':
        seed_sample_data()
    
    print("\nDatabase initialization complete!")
    print("You can now start the API server with: uvicorn main:app --reload")
